### ISSUE TITLE
App container exits right after starting (win 10)

### ISSUE THREAD

**Issue by mityukov** [shipping-docker/vessel#94]
## Description

I've tried to install laravel-based project on a developer's machine (Win 10) and got the following issue in the result:

1. I could `bash vessel init` it

2. I could run `./vessel start` without errors

3. When trying anything else, however (`./vessel art`, `./vessel serve`, etc.) — got something like "app container not found"

4. `docker ps -a` reported that app container has exited right after starting with 127 status.

5. `docker logs -t <cont_name>` reported the following: `/usr/bin/env: 'bash\r': No such file or directory`

## OS

My OS is:
- [ ] Windows 10 with Git Bash

## Docker

The output of `docker version`: 

not sure… installed docker from official site yesterday.

**Comment by fideloper** [comment]
I was trying t find an old issue/PR here where we discussed a lot of windows stuff, I couldn't find it on my quick search, but I think it's here somewhere.....

It sounds like it's not mounting the Windows directory correctly. Have you tries using WSL (if you can - it may require windows professional).

**Comment by mityukov** [comment]
This looks more like an incompatible newline symbol in one of bash scripts, running after container has started. I'll make more tests on a window machine once I have one in my hands. This issue (this ticket) — I've filed it after having TeamView session with a new dev =)

**Comment by JoeyHoutenbos** [comment]
@mityukov I think converting the line endings to Unix style should solve the problem. I have this problem myself quite often between colleagues working on Mac, Linux or Windows.

Use dos2unix (https://waterlan.home.xs4all.nl/dos2unix.html) to convert the line endings and try building the images again.

**Comment by mityukov** [comment]
Still no luck getting ahold a Win 10 machine (and not enough time, honestly…)

I have this question, however: is it possible to produce some kind of "combined image", so that the dev would only run this one image to have the development install ready to go on whatever os /she may have?

Currently, they clone the repo, including those files under `docker` directory and there are weird things happen, because of line endings auto-converting (during the `git clone`, yes) and god knows what else… Then they need `php7` , `composer` just to have it all installed as far as I understand from the installation instructions. Instead, I'd like to configure all myself (already did) and then make the devs to download a binary image instead, where everything is ready to spin up, "just mount the app directory and specify app port (in case there is some local webserver on dev's port 80 already)". Is there an option like this?

So, in ideal world, the dev would:
1. Install Docker and Git (the Git one I'd still like them to have installed on they're machine; partially because of Git Bash provided out of the box)
2. Git clone the repo
3. Go to that repo's directory, fire some command (doesn't have to be `./vessel ...`. The main requirement is that the command is the same for every possible environment )
4. It's all up and running.

**Comment by djam90** [comment]
I was having this exact same issue and just ran in git bash: 

```
dos2unix.exe docker/app/start-container ./vessel
```

Then ran:

```
./vessel build app
```

and finally `./vessel start` and it works!

**Comment by djam90** [comment]
OK actually whilst the `./vessel start` works, using any other vessel commands results in the following error:

```
$ ./vessel composer install
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'
```

Not really sure how to proceed with this.

I think I may end up, sadly, abandoning Vessel for development in Windows 10  :(

**Comment by fideloper** [comment]
At this point I think we'd have to suggest WSL or WSL2 for use with Vessel.

The TTY error might be, however, because the program used to run that command wasn't compatible with a TTY (powershell? cmd? git bash?)
